id: c8791c816ca5482e95ccbebaae738d0a
initial_creation_type: ocr
source_metadata:
  volumes:
    9781b56a7e9f4427b7574e4c55305d5f:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: ''
      total_pages: 2043
      volume_number: 13
